"""this is a test function for nbdev_test"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_test_fun.ipynb.

# %% auto 0
__all__ = ['say_hello', 'fun']

# %% ../nbs/00_test_fun.ipynb 2
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/00_test_fun.ipynb 4
def fun(): # a test function
    print("hhahahahahahah")
